kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dockerfile-buildconfig
  namespace: mq
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/Telstra-mq-hub/mq-dev-patterns"
  strategy: 
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: testing:latest
  postCommit: {}